"""Generator (step 67): a validated plan in, a Databricks notebook out.

The model writes cells; each cell cites the catalog documents it follows.
The notebook itself is assembled by code, in Databricks source format (a
`.py` file with `# COMMAND ----------` between cells): it diffs cleanly in a
pull request and parses as ordinary Python, so every later gate reads it
with `ast`. Parameters become widgets in a cell the code writes, so a
notebook can never smuggle a table name in as a literal (catalog standard
"configuration comes from metadata").

Before the Critic sees anything, a program checks the draft: every cell
parses, every citation is a real catalog document, cited patterns are ones
the plan chose, and every pattern in the plan is cited by at least one cell.
"""

from __future__ import annotations

import ast
import json
from collections.abc import Sequence

from pydantic import BaseModel, ConfigDict, Field

from copilot.agents.base import Catalog, Exchange, ask_json
from copilot.agents.planner import Plan
from copilot.catalog.model import Kind
from copilot.llm import LLM

HEADER = "# Databricks notebook source"
SEPARATOR = "\n\n# COMMAND ----------\n\n"


class Cell(BaseModel):
    model_config = ConfigDict(extra="forbid")
    title: str = Field(min_length=1, max_length=120)
    code: str = Field(min_length=1)
    cites: list[str] = Field(min_length=1)
    """Catalog ids this cell follows: patterns from the plan, or standards."""


class NotebookDraft(BaseModel):
    model_config = ConfigDict(extra="forbid")
    parameters: list[str] = Field(default_factory=list)
    """Notebook widgets, read into variables of the same name before any cell runs.
    Names follow the contract in `allowed_parameters`."""
    cells: list[Cell] = Field(min_length=1, max_length=20)


def render(draft: NotebookDraft, plan: Plan) -> str:
    """The notebook as a Databricks source file."""
    intro = [
        f"# MAGIC %md\n# MAGIC # {plan.target}\n# MAGIC {plan.intent}",
        "# MAGIC",
        f"# MAGIC Layer: {plan.layer} - strategy: {plan.strategy} - "
        f"sources: {', '.join(plan.sources)} - keys: {', '.join(plan.keys)}",
        "# MAGIC",
        "# MAGIC Generated by agentic-pipeline-copilot from a plan checked against the catalog.",
    ]
    cells = ["\n".join(intro)]
    if draft.parameters:
        widgets = [f'dbutils.widgets.text("{p}", "")' for p in draft.parameters]
        reads = [f'{p} = dbutils.widgets.get("{p}")' for p in draft.parameters]
        cells.append("# DBTITLE 1,Parameters\n" + "\n".join(widgets + reads))
    for cell in draft.cells:
        title = " ".join(cell.title.split())
        cites = ", ".join(cell.cites)
        cells.append(f"# DBTITLE 1,{title}\n# Follows: {cites}\n{cell.code.strip()}")
    return HEADER + "\n" + SEPARATOR.join(cells) + "\n"


def allowed_parameters(plan: Plan) -> list[str]:
    """The parameter contract (ADR-005): one table name per source, the target, the
    watermark and the key columns - what the control plane passes, and what the
    Validator supplies in the sandbox."""
    return [f"{s}_table" for s in plan.sources] + ["target_table", "watermark", "key_columns"]


def check_draft(draft: NotebookDraft, plan: Plan, catalog: Catalog) -> list[str]:
    """Everything wrong with the draft before review. Empty means it can go to the Critic."""
    errors: list[str] = []
    contract = allowed_parameters(plan)
    for p in draft.parameters:
        if p not in contract:
            errors.append(f"parameter '{p}' is not in the contract ({', '.join(contract)})")
    if len(set(draft.parameters)) != len(draft.parameters):
        errors.append("parameters repeat a name")
    allowed = set(plan.patterns) | {f"table:{s}" for s in plan.sources}
    for n, cell in enumerate(draft.cells, 1):
        try:
            ast.parse(cell.code)
        except SyntaxError as exc:
            errors.append(f"cell {n} '{cell.title}' line {exc.lineno}: {exc.msg}")
        for cite in cell.cites:
            if cite not in catalog.docs:
                errors.append(f"cell {n} cites '{cite}', which is not in the catalog")
            elif not (catalog.is_a(cite, Kind.STANDARD) or cite in allowed):
                errors.append(f"cell {n} cites '{cite}', which the plan did not choose")
    cited = {c for cell in draft.cells for c in cell.cites}
    errors += [f"no cell follows the plan's '{p}'" for p in plan.patterns if p not in cited]
    return errors


SYSTEM = """You are the Generator of a pipeline copilot for a metadata-driven lakehouse.
Write the PySpark cells of ONE Databricks notebook that implements the plan.

The runtime provides `spark` and `dbutils`. Rules a program enforces:
- every cell cites the catalog ids it follows ("pattern:..." ids from the plan,
  "table:..." for its sources, or "standard:..." ids); every plan pattern is cited;
- each cell is valid Python on its own;
- table names, paths and keys come from parameters (listed in "parameters", read for
  you into variables of the same name) - never as string literals. Allowed names:
  "<source>_table" for each source (e.g. orders_table), "target_table", "watermark"
  (a string; compare it as an integer epoch) and "key_columns" (comma-separated);
- the target table already exists: MERGE into it with DeltaTable.forName(spark, target_table);
- no collect(), toPandas() or take() without a small explicit limit; no select("*");
  no credentials; writes are idempotent (Delta MERGE on the key, never a blind append);
- use only the columns the catalog lists.

Reply with one JSON object matching this JSON Schema, and nothing else:
"""


def _context(plan: Plan, catalog: Catalog) -> str:
    docs = [catalog.docs[f"table:{s}"] for s in plan.sources]
    docs += [catalog.docs[p] for p in plan.patterns]
    docs += [catalog.docs[s] for s in plan.standards]
    return "\n\n".join(f"### {d.id} - {d.title}\n{d.text[:2000]}" for d in docs)


class Generator:
    def __init__(self, llm: LLM, catalog: Catalog, max_attempts: int) -> None:
        self.llm, self.catalog, self.max_attempts = llm, catalog, max_attempts

    def generate(
        self,
        plan: Plan,
        exchange: Exchange | None = None,
        review: Sequence[str] = (),
        previous: NotebookDraft | None = None,
    ) -> NotebookDraft:
        """Write the notebook, or revise `previous` to resolve the Critic's `review`."""
        user = (
            f"# Plan\n\n{plan.model_dump_json(indent=2)}\n\n"
            f"# Parameters you may declare\n\n{', '.join(allowed_parameters(plan))}\n\n"
            f"# Catalog documents the plan uses\n\n{_context(plan, self.catalog)}"
        )
        if previous is not None:
            user += (
                f"\n\n# Your previous notebook\n\n{previous.model_dump_json(indent=2)}"
                "\n\n# It was sent back for these reasons (review findings, or errors from "
                "running it on sample data in the sandbox) - fix every one\n\n"
                + "\n".join(f"- {r}" for r in review)
            )
        messages = [
            {"role": "system", "content": SYSTEM + json.dumps(NotebookDraft.model_json_schema())},
            {"role": "user", "content": user},
        ]
        return ask_json(
            self.llm,
            "generate",
            messages,
            NotebookDraft,
            lambda d: check_draft(d, plan, self.catalog),
            self.max_attempts,
            exchange,
        )
